# Generated by Django 4.0.4 on 2022-06-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='travels',
            options={'verbose_name': 'travel', 'verbose_name_plural': 'travels'},
        ),
    ]
