# Generated by Django 4.0.4 on 2022-06-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_categories_options_alter_travels_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='image',
            field=models.ImageField(null=True, upload_to='Travels'),
        ),
    ]
