# Generated by Django 4.0.4 on 2022-06-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=25)),
                ('day_birth', models.DateField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('ISBN', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.CharField(blank=True, max_length=200)),
                ('publication_date', models.DateField()),
                ('edition', models.IntegerField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='books')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='Editorials',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('founder', models.CharField(max_length=50)),
                ('foundation_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('main_organization', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'editorial',
                'verbose_name_plural': 'editorials',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
            },
        ),
    ]
