# Generated by Django 4.0.4 on 2022-06-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_cover_alter_books_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorials',
            name='main_organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
