# Generated by Django 4.0.4 on 2022-06-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_editorials_main_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorials',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='editorials',
            name='foundation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editorials',
            name='founder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
