# Generated by Django 4.0.4 on 2022-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_editorials_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
