# Generated by Django 4.0.4 on 2022-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_genres_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='synopsis',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
