# Generated by Django 4.0.4 on 2022-06-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorials',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(null=True, upload_to='books'),
        ),
    ]
