# Generated by Django 4.0.4 on 2022-06-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_editorials_logo_alter_books_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
