# Generated by Django 4.0.4 on 2022-06-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_day_birth_authors_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.FloatField(),
        ),
    ]
